<a href="https://colab.research.google.com/github/GriffinPlecko/PyTorch-Repository/blob/main/Tensor_MathOps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensor Math Operations


*   Add, Subtract, Multiply, Divide, Remainders, Exponents
*   Shorthand and Longhand
*   Reassignment






In [1]:
import torch

In [2]:
#Import Numpy
import numpy as np


In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [6]:
# Subtraction Longhand
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [7]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [8]:
# Multiplication Longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [9]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [10]:
# Division Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [11]:
# Remainder Modules
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [12]:
# Remainder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [13]:
# Exponents / Power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [14]:
# Other way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [15]:
# Reassignment (Use underscore at end of variable call)
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [16]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [17]:
tensor_a

tensor([ 6,  8, 10, 12])